/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pemesanan;


import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;



/**
 *
 * @author MOHAMAD HASAN BISRI
 */
public class Home extends javax.swing.JFrame {
    String tgl, bln, thn, jam;
    
    int eksekutif, ekonomi, harga, total, kembali;
    int bayar[] = new int[1];
    int jumlah[] = new int[1];
    

    /**
     * Creates new form Dashboard
     */
    
    public Home() {
        initComponents();
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rSButtonRiple2 = new rojeru_san.RSButtonRiple();
        rSButtonRiple4 = new rojeru_san.RSButtonRiple();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb_jurusan = new rojerusan.RSComboMetro();
        eko = new javax.swing.JRadioButton();
        eks = new javax.swing.JRadioButton();
        txt_harga = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_nomor = new javax.swing.JTextField();
        cb_tgl = new rojerusan.RSComboMetro();
        cb_bln = new rojerusan.RSComboMetro();
        cb_thn = new rojerusan.RSComboMetro();
        txt_jumlah = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        cb_jam = new rojerusan.RSComboMetro();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_bayar = new javax.swing.JTextField();
        txt_kembalian = new javax.swing.JTextField();
        btn_bayar = new rojeru_san.RSButtonRiple();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        btn_clear = new rojeru_san.RSButtonRiple();
        btn_keluar = new rojeru_san.RSButtonRiple();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pemesanan/Img/icons8_batman_logo_120px_1.png"))); // NOI18N

        rSButtonRiple2.setBackground(new java.awt.Color(110, 89, 222));
        rSButtonRiple2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pemesanan/Img/icons8_ticket_20px.png"))); // NOI18N
        rSButtonRiple2.setText("Pesan Tiket");
        rSButtonRiple2.setColorHover(new java.awt.Color(110, 89, 222));
        rSButtonRiple2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rSButtonRiple2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rSButtonRiple4.setBackground(new java.awt.Color(54, 33, 89));
        rSButtonRiple4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pemesanan/Img/icons8_exit_20px_2.png"))); // NOI18N
        rSButtonRiple4.setText("Keluar");
        rSButtonRiple4.setColorHover(new java.awt.Color(110, 89, 222));
        rSButtonRiple4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rSButtonRiple4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonRiple4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSButtonRiple2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(rSButtonRiple4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(rSButtonRiple2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonRiple4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(110, 89, 222));

        jPanel5.setBackground(new java.awt.Color(110, 89, 222));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Data Pemesanan Tiket", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("JURUSAN");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KELAS");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HARGA");

        cb_jurusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "== Pilih Rute Jurusan ==", "Surabaya", "Jombang", "Malang", "Blitar", "Kediri" }));
        cb_jurusan.setColorArrow(new java.awt.Color(110, 89, 222));
        cb_jurusan.setColorBorde(new java.awt.Color(255, 255, 255));
        cb_jurusan.setColorFondo(new java.awt.Color(110, 89, 222));
        cb_jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_jurusanActionPerformed(evt);
            }
        });

        eko.setBackground(new java.awt.Color(110, 89, 222));
        eko.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        eko.setForeground(new java.awt.Color(255, 255, 255));
        eko.setText("Ekonomi");
        eko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekoActionPerformed(evt);
            }
        });

        eks.setBackground(new java.awt.Color(110, 89, 222));
        eks.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        eks.setForeground(new java.awt.Color(255, 255, 255));
        eks.setText("Eksekutif");
        eks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eksActionPerformed(evt);
            }
        });

        txt_harga.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(eko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eks))
                    .addComponent(cb_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_harga))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eko)
                    .addComponent(eks))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(110, 89, 222));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Input Data Penumpang", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAMA PENUMPANG");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NOMOR KURSI");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TANGGAL BRANGKAT");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("JAM KEBERANGKATAN");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("JUMLAH BELI");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TOTAL HARGA");

        cb_tgl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cb_tgl.setColorArrow(new java.awt.Color(110, 89, 222));
        cb_tgl.setColorBorde(new java.awt.Color(255, 255, 255));
        cb_tgl.setColorFondo(new java.awt.Color(110, 89, 222));
        cb_tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tglActionPerformed(evt);
            }
        });

        cb_bln.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cb_bln.setColorArrow(new java.awt.Color(110, 89, 222));
        cb_bln.setColorBorde(new java.awt.Color(255, 255, 255));
        cb_bln.setColorFondo(new java.awt.Color(110, 89, 222));
        cb_bln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_blnActionPerformed(evt);
            }
        });

        cb_thn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "2020", "2021", "2022", "2023" }));
        cb_thn.setColorArrow(new java.awt.Color(110, 89, 222));
        cb_thn.setColorBorde(new java.awt.Color(255, 255, 255));
        cb_thn.setColorFondo(new java.awt.Color(110, 89, 222));
        cb_thn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_thnActionPerformed(evt);
            }
        });

        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });

        txt_total.setEditable(false);

        cb_jam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "== Pilih Jam ==", "06:00", "08:00", "10:00", "12:00" }));
        cb_jam.setColorArrow(new java.awt.Color(110, 89, 222));
        cb_jam.setColorBorde(new java.awt.Color(255, 255, 255));
        cb_jam.setColorFondo(new java.awt.Color(110, 89, 222));
        cb_jam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_jamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(49, 49, 49)
                        .addComponent(txt_nama))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nomor)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(cb_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_bln, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(cb_thn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_jumlah)
                            .addComponent(txt_total)
                            .addComponent(cb_jam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cb_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_thn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_jam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(110, 89, 222));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Data Pembayaran", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("UANG BAYAR");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("KEMBALIAN");

        txt_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bayarActionPerformed(evt);
            }
        });
        txt_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bayarKeyReleased(evt);
            }
        });

        txt_kembalian.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(89, 89, 89)
                        .addComponent(txt_bayar))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(99, 99, 99)
                        .addComponent(txt_kembalian)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_bayar.setBackground(new java.awt.Color(255, 0, 0));
        btn_bayar.setText("Bayar");
        btn_bayar.setColorHover(new java.awt.Color(255, 51, 51));
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(110, 89, 222));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Print Pesanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        btn_clear.setBackground(new java.awt.Color(255, 0, 0));
        btn_clear.setText("Clear");
        btn_clear.setColorHover(new java.awt.Color(255, 51, 51));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_keluar.setBackground(new java.awt.Color(255, 0, 0));
        btn_keluar.setText("Keluar");
        btn_keluar.setColorHover(new java.awt.Color(255, 51, 51));
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Dashboard => Home");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cb_jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_jurusanActionPerformed
        // TODO add your handling code here:
        if(cb_jurusan.getSelectedItem().equals("== Pilih Rute Jurusan ==")){
            buttonGroup1.clearSelection();
            txt_harga.setText("");
        }
        else if(cb_jurusan.getSelectedItem().equals("Surabaya")){
            eksekutif = 24000;
            ekonomi = 12000;
        }
        else if(cb_jurusan.getSelectedItem().equals("Jombang")){
            eksekutif = 18000;
            ekonomi = 10000;
        }
        else if(cb_jurusan.getSelectedItem().equals("Malang")){
            eksekutif = 40000;
            ekonomi = 20000;
        }
        else if(cb_jurusan.getSelectedItem().equals("Blitar")){
            eksekutif = 50000;
            ekonomi = 25000;
        }
        else if(cb_jurusan.getSelectedItem().equals("Kediri")){
            eksekutif = 45000;
            ekonomi = 20000;
        }
    }//GEN-LAST:event_cb_jurusanActionPerformed

    private void ekoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekoActionPerformed
        // TODO add your handling code here:
        if(eko.isSelected()){
            txt_harga.setText(String.valueOf(ekonomi));
        }
    }//GEN-LAST:event_ekoActionPerformed

    private void eksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eksActionPerformed
        // TODO add your handling code here:
        if(eks.isSelected()){
            txt_harga.setText(String.valueOf(eksekutif));
        }
    }//GEN-LAST:event_eksActionPerformed

    private void cb_tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tglActionPerformed
        // TODO add your handling code here:
        if(cb_tgl.getSelectedItem().equals("Pilih")){
            tgl = "";
        }
        else if(cb_tgl.getSelectedItem().equals("01")){
            tgl = "01";
        }
        else if(cb_tgl.getSelectedItem().equals("02")){
            tgl = "02";
        }
        else if(cb_tgl.getSelectedItem().equals("03")){
            tgl = "03";
        }
        else if(cb_tgl.getSelectedItem().equals("04")){
            tgl = "04";
        }
        else if(cb_tgl.getSelectedItem().equals("05")){
            tgl = "05";
        }
        else if(cb_tgl.getSelectedItem().equals("06")){
            tgl = "06";
        }
        else if(cb_tgl.getSelectedItem().equals("07")){
            tgl = "07";
        }
        else if(cb_tgl.getSelectedItem().equals("08")){
            tgl = "08";
        }
        else if(cb_tgl.getSelectedItem().equals("09")){
            tgl = "09";
        }
        else if(cb_tgl.getSelectedItem().equals("10")){
            tgl = "10";
        }
        else if(cb_tgl.getSelectedItem().equals("11")){
            tgl = "11";
        }
        else if(cb_tgl.getSelectedItem().equals("12")){
            tgl = "12";
        }
        else if(cb_tgl.getSelectedItem().equals("13")){
            tgl = "13";
        }
        else if(cb_tgl.getSelectedItem().equals("14")){
            tgl = "14";
        }
        else if(cb_tgl.getSelectedItem().equals("15")){
            tgl = "15";
        }
        else if(cb_tgl.getSelectedItem().equals("16")){
            tgl = "16";
        }
        else if(cb_tgl.getSelectedItem().equals("17")){
            tgl = "17";
        }
        else if(cb_tgl.getSelectedItem().equals("18")){
            tgl = "18";
        }
        else if(cb_tgl.getSelectedItem().equals("19")){
            tgl = "19";
        }
        else if(cb_tgl.getSelectedItem().equals("20")){
            tgl = "20";
        }
        else if(cb_tgl.getSelectedItem().equals("21")){
            tgl = "21";
        }
        else if(cb_tgl.getSelectedItem().equals("22")){
            tgl = "22";
        }
        else if(cb_tgl.getSelectedItem().equals("23")){
            tgl = "23";
        }
        else if(cb_tgl.getSelectedItem().equals("24")){
            tgl = "24";
        }
        else if(cb_tgl.getSelectedItem().equals("25")){
            tgl = "25";
        }
        else if(cb_tgl.getSelectedItem().equals("26")){
            tgl = "26";
        }
        else if(cb_tgl.getSelectedItem().equals("27")){
            tgl = "27";
        }
        else if(cb_tgl.getSelectedItem().equals("28")){
            tgl = "28";
        }
        else if(cb_tgl.getSelectedItem().equals("29")){
            tgl = "29";
        }
        else if(cb_tgl.getSelectedItem().equals("30")){
            tgl = "30";
        }
        else if(cb_tgl.getSelectedItem().equals("31")){
            tgl = "31";
        }
    }//GEN-LAST:event_cb_tglActionPerformed

    private void cb_blnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_blnActionPerformed
        // TODO add your handling code here:
        if(cb_bln.getSelectedItem().equals("Pilih")){
            bln = "";
        }
        else if(cb_bln.getSelectedItem().equals("Januari")){
            bln = "Januari";
        }
        else if(cb_bln.getSelectedItem().equals("Februari")){
            bln = "Februari";
        }
        else if(cb_bln.getSelectedItem().equals("Maret")){
            bln = "Maret";
        }
        else if(cb_bln.getSelectedItem().equals("April")){
            bln = "April";
        }
        else if(cb_bln.getSelectedItem().equals("Mei")){
            bln = "Mei";
        }
        else if(cb_bln.getSelectedItem().equals("Juni")){
            bln = "Juni";
        }
        else if(cb_bln.getSelectedItem().equals("Juli")){
            bln = "Juli";
        }
        else if(cb_bln.getSelectedItem().equals("Agustus")){
            bln = "Agustus";
        }
        else if(cb_bln.getSelectedItem().equals("September")){
            bln = "September";
        }
        else if(cb_bln.getSelectedItem().equals("Oktober")){
            bln = "Oktober";
        }
        else if(cb_bln.getSelectedItem().equals("November")){
            bln = "November";
        }
        else if(cb_bln.getSelectedItem().equals("Desember")){
            bln = "Desember";
        }
    }//GEN-LAST:event_cb_blnActionPerformed

    private void cb_thnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_thnActionPerformed
        // TODO add your handling code here:
        if(cb_thn.getSelectedItem().equals("Pilih")){
            thn = "";
        }
        else if(cb_thn.getSelectedItem().equals("2020")){
            thn = "2020";
        }
        else if(cb_thn.getSelectedItem().equals("2021")){
            thn = "2021";
        }
        else if(cb_thn.getSelectedItem().equals("2022")){
            thn = "2022";
        }
        else if(cb_thn.getSelectedItem().equals("2023")){
            thn = "2023";
        }
    }//GEN-LAST:event_cb_thnActionPerformed

    private void cb_jamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_jamActionPerformed
        // TODO add your handling code here:
        if(cb_jam.getSelectedItem().equals("== Pilih Jam ==")){
            jam = "";
        }
        else if(cb_jam.getSelectedItem().equals("06:00")){
            jam = "06:00";
        }
        else if(cb_jam.getSelectedItem().equals("08:00")){
            jam = "08:00";
        }
        else if(cb_jam.getSelectedItem().equals("10:00")){
            jam = "10:00";
        }
        else if(cb_jam.getSelectedItem().equals("12:00")){
            jam = "12:00";
        }
    }//GEN-LAST:event_cb_jamActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
        jumlah[0] = Integer.parseInt((txt_jumlah.getText()));
        harga = Integer.parseInt(txt_harga.getText());
        total = jumlah[0]*harga;
        txt_total.setText(String.valueOf(total));
    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void txt_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bayarActionPerformed
        // TODO add your handling code here:
        bayar[0] = Integer.parseInt((txt_bayar.getText()));
        kembali = Integer.parseInt(txt_total.getText());
        total=bayar[0]-kembali;
        txt_kembalian.setText(String.valueOf(total));
    }//GEN-LAST:event_txt_bayarActionPerformed

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a =Integer.valueOf(txt_harga.getText());
        b =Integer.valueOf(txt_jumlah.getText());
        c=a*b;
        txt_total.setText(""+c);
    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void txt_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bayarKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a =Integer.valueOf(txt_bayar.getText());
        b =Integer.valueOf(txt_total.getText());
        c=a-b;
        txt_kembalian.setText(""+c);
    }//GEN-LAST:event_txt_bayarKeyReleased

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        // TODO add your handling code here:
        txt_area.setText(
                "=========================================="+"\n"+
                "                                               CETAK                 "+"\n"+
                "                                           TIKET KERETA           "+"\n"+
                "=========================================="+"\n"+
                "NAMA PENUMPANG                                  : "+txt_nama.getText()+"\n"+
                "TANGGAL KEBERANGKATAN                : "+tgl+"-"+bln+"-"+thn+"\n"+        
                "JAM KEBERANGKATAN                           : "+jam+"\n"+        
                "JUMLAH BELI                                            : "+txt_jumlah.getText()+"\n"+ 
                "-------------------------------------------------------------------------"+"\n"+
                "TOTAL BAYAR                                            : "+txt_total.getText()+"\n"+ 
                "-------------------------------------------------------------------------"+"\n"+
                "UANG BAYAR                                             : "+txt_bayar.getText()+"\n"+         
                "UANG KEMBALIAN                                   : "+txt_kembalian.getText()+"\n"+                 
                "=========================================="+"\n"+        
                "                                    TERIMAKASIH               "+"\n"+
                "          SELAMAT MENIKMATI PERJALANAN ANDA    "+"\n"+        
                "=========================================="+"\n");
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        txt_harga.setText("");
        cb_jurusan.setSelectedItem("== Pilih Rute Jurusan ==");
        txt_nama.setText("");
        cb_tgl.setSelectedItem("Pilih");
        cb_bln.setSelectedItem("Pilih");
        cb_thn.setSelectedItem("Pilih");
        cb_jam.setSelectedItem("== Pilih Jam ==");
        txt_total.setText("");
        txt_jumlah.setText("");
        txt_bayar.setText("");
        txt_kembalian.setText("");
        txt_area.setText("");
        JOptionPane.showMessageDialog(null, "Clear Data Berhasil", "Clear", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void rSButtonRiple4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rSButtonRiple4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btn_bayar;
    private rojeru_san.RSButtonRiple btn_clear;
    private rojeru_san.RSButtonRiple btn_keluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private rojerusan.RSComboMetro cb_bln;
    private rojerusan.RSComboMetro cb_jam;
    private rojerusan.RSComboMetro cb_jurusan;
    private rojerusan.RSComboMetro cb_tgl;
    private rojerusan.RSComboMetro cb_thn;
    private javax.swing.JRadioButton eko;
    private javax.swing.JRadioButton eks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSButtonRiple rSButtonRiple2;
    private rojeru_san.RSButtonRiple rSButtonRiple4;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nomor;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
